# ====== Code Summary ======
# initial schema - full rework model
#
# Revision: 0d66d7d3c37c
# Revises: 
# Created: 2026-07-04 16:54:33.827173

# ====== Third-Party Library Imports ======
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers used by Alembic.
revision = '0d66d7d3c37c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this revision's schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('root', 'user', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('blob',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('original', 'canonical_pdf', 'page_render', 'figure_crop', name='blobkind', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('content_hash', name=op.f('pk_blob'))
    )
    op.create_table('collection',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('supported_formats', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('max_file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('needs_reindex', sa.Boolean(), nullable=False),
    sa.Column('pipeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection')),
    sa.UniqueConstraint('name', name=op.f('uq_collection_name'))
    )
    op.create_table('api_key',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_api_key_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key'))
    )
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=False)
    op.create_table('config_version',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_config_version_collection_id_collection'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_version'))
    )
    op.create_index(op.f('ix_config_version_collection_id'), 'config_version', ['collection_id'], unique=False)
    op.create_table('document',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('pdf_blob_hash', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('source_kind', sa.Enum('digital_born', 'scanned', 'mixed', name='sourcekind', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('simhash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_document_collection_id_collection'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pdf_blob_hash'], ['blob.content_hash'], name=op.f('fk_document_pdf_blob_hash_blob'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sa.UniqueConstraint('collection_id', 'source_hash', 'pipeline_version', name=op.f('uq_document_collection_id'))
    )
    op.create_index(op.f('ix_document_pdf_blob_hash'), 'document', ['pdf_blob_hash'], unique=False)
    op.create_index(op.f('ix_document_source_hash'), 'document', ['source_hash'], unique=False)
    op.create_table('metadata_field',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('string', 'integer', 'float', 'bool', 'keyword_list', 'datetime', name='fieldtype', native_enum=False), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('filterable', sa.Boolean(), nullable=False),
    sa.Column('lexical', sa.Boolean(), nullable=False),
    sa.Column('semantic', sa.Boolean(), nullable=False),
    sa.Column('enum_values', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('origin', sa.Enum('system', 'user', 'generated', name='fieldorigin', native_enum=False), nullable=False),
    sa.Column('scope', sa.Enum('document', 'chunk', name='fieldscope', native_enum=False), nullable=False),
    sa.CheckConstraint("NOT required OR origin = 'user'", name=op.f('ck_metadata_field_required_user_only')),
    sa.CheckConstraint("scope != 'chunk' OR origin = 'generated'", name=op.f('ck_metadata_field_chunk_scope_generated_only')),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_metadata_field_collection_id_collection'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metadata_field')),
    sa.UniqueConstraint('collection_id', 'field_name', name=op.f('uq_metadata_field_collection_id'))
    )
    op.create_table('block',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('block_type', sa.String(length=32), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('column_index', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=256), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_boilerplate', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_block_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['block.id'], name=op.f('fk_block_parent_id_block'), ondelete='SET NULL', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block'))
    )
    op.create_index(op.f('ix_block_document_id'), 'block', ['document_id'], unique=False)
    op.create_index(op.f('ix_block_parent_id'), 'block', ['parent_id'], unique=False)
    op.create_table('chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('config_hash', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('simhash', sa.String(length=64), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_chunk_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['chunk.id'], name=op.f('fk_chunk_parent_id_chunk'), ondelete='SET NULL', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk'))
    )
    op.create_index('ix_chunk_document_config', 'chunk', ['document_id', 'config_hash'], unique=False)
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunk_parent_id'), 'chunk', ['parent_id'], unique=False)
    op.create_table('document_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.Enum('system', 'user', 'generated', name='fieldorigin', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_metadata_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['metadata_field.id'], name=op.f('fk_document_metadata_field_id_metadata_field'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_metadata')),
    sa.UniqueConstraint('document_id', 'field_id', name=op.f('uq_document_metadata_document_id'))
    )
    op.create_index(op.f('ix_document_metadata_field_id'), 'document_metadata', ['field_id'], unique=False)
    op.create_table('job',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('attempt', sa.SmallInteger(), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_job_collection_id_collection'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_job_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index(op.f('ix_job_collection_id'), 'job', ['collection_id'], unique=False)
    op.create_index(op.f('ix_job_document_id'), 'job', ['document_id'], unique=False)
    op.create_table('page',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('render_blob_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_page_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['render_blob_hash'], ['blob.content_hash'], name=op.f('fk_page_render_blob_hash_blob'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page')),
    sa.UniqueConstraint('document_id', 'page_number', name=op.f('uq_page_document_id'))
    )
    op.create_index(op.f('ix_page_document_id'), 'page', ['document_id'], unique=False)
    op.create_index(op.f('ix_page_render_blob_hash'), 'page', ['render_blob_hash'], unique=False)
    op.create_table('block_enrichment',
    sa.Column('block_id', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.Enum('classify', 'ocr', 'vlm', 'chart_to_data', 'table_summary', name='enrichmentkind', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('ok', 'failed', 'skipped', name='enrichmentstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], name=op.f('fk_block_enrichment_block_id_block'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_enrichment')),
    sa.UniqueConstraint('block_id', 'kind', name=op.f('uq_block_enrichment_block_id'))
    )
    op.create_index(op.f('ix_block_enrichment_block_id'), 'block_enrichment', ['block_id'], unique=False)
    op.create_table('block_figure',
    sa.Column('block_id', sa.String(length=256), nullable=False),
    sa.Column('crop_blob_hash', sa.String(length=64), nullable=True),
    sa.Column('caption_block_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], name=op.f('fk_block_figure_block_id_block'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caption_block_id'], ['block.id'], name=op.f('fk_block_figure_caption_block_id_block'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_blob_hash'], ['blob.content_hash'], name=op.f('fk_block_figure_crop_blob_hash_blob'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('block_id', name=op.f('pk_block_figure'))
    )
    op.create_index(op.f('ix_block_figure_caption_block_id'), 'block_figure', ['caption_block_id'], unique=False)
    op.create_index(op.f('ix_block_figure_crop_blob_hash'), 'block_figure', ['crop_blob_hash'], unique=False)
    op.create_table('block_table',
    sa.Column('block_id', sa.String(length=256), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_cols', sa.Integer(), nullable=False),
    sa.Column('has_header', sa.Boolean(), nullable=False),
    sa.Column('cells', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linearized_md', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], name=op.f('fk_block_table_block_id_block'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id', name=op.f('pk_block_table'))
    )
    op.create_table('chunk_block',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('block_id', sa.String(length=256), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], name=op.f('fk_chunk_block_block_id_block'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], name=op.f('fk_chunk_block_chunk_id_chunk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', 'block_id', name=op.f('pk_chunk_block'))
    )
    op.create_index('ix_chunk_block_block_id', 'chunk_block', ['block_id'], unique=False)
    op.create_table('chunk_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.Enum('system', 'user', 'generated', name='fieldorigin', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], name=op.f('fk_chunk_metadata_chunk_id_chunk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['metadata_field.id'], name=op.f('fk_chunk_metadata_field_id_metadata_field'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_metadata')),
    sa.UniqueConstraint('chunk_id', 'field_id', name=op.f('uq_chunk_metadata_chunk_id'))
    )
    op.create_index(op.f('ix_chunk_metadata_field_id'), 'chunk_metadata', ['field_id'], unique=False)
    op.create_table('chunk_query',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], name=op.f('fk_chunk_query_chunk_id_chunk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk_query'))
    )
    op.create_index(op.f('ix_chunk_query_chunk_id'), 'chunk_query', ['chunk_id'], unique=False)
    op.create_table('entity_mention',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('surface_text', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.String(length=512), nullable=True),
    sa.Column('span', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], name=op.f('fk_entity_mention_chunk_id_chunk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_mention'))
    )
    op.create_index(op.f('ix_entity_mention_chunk_id'), 'entity_mention', ['chunk_id'], unique=False)
    op.create_table('job_stage_event',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_stage_event_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_stage_event'))
    )
    op.create_index(op.f('ix_job_stage_event_job_id'), 'job_stage_event', ['job_id'], unique=False)
    op.create_table('enrichment_attempt',
    sa.Column('block_enrichment_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ok', 'failed', name='attemptstatus', native_enum=False), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_enrichment_id'], ['block_enrichment.id'], name=op.f('fk_enrichment_attempt_block_enrichment_id_block_enrichment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrichment_attempt'))
    )
    op.create_index(op.f('ix_enrichment_attempt_block_enrichment_id'), 'enrichment_attempt', ['block_enrichment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision's schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrichment_attempt_block_enrichment_id'), table_name='enrichment_attempt')
    op.drop_table('enrichment_attempt')
    op.drop_index(op.f('ix_job_stage_event_job_id'), table_name='job_stage_event')
    op.drop_table('job_stage_event')
    op.drop_index(op.f('ix_entity_mention_chunk_id'), table_name='entity_mention')
    op.drop_table('entity_mention')
    op.drop_index(op.f('ix_chunk_query_chunk_id'), table_name='chunk_query')
    op.drop_table('chunk_query')
    op.drop_index(op.f('ix_chunk_metadata_field_id'), table_name='chunk_metadata')
    op.drop_table('chunk_metadata')
    op.drop_index('ix_chunk_block_block_id', table_name='chunk_block')
    op.drop_table('chunk_block')
    op.drop_table('block_table')
    op.drop_index(op.f('ix_block_figure_crop_blob_hash'), table_name='block_figure')
    op.drop_index(op.f('ix_block_figure_caption_block_id'), table_name='block_figure')
    op.drop_table('block_figure')
    op.drop_index(op.f('ix_block_enrichment_block_id'), table_name='block_enrichment')
    op.drop_table('block_enrichment')
    op.drop_index(op.f('ix_page_render_blob_hash'), table_name='page')
    op.drop_index(op.f('ix_page_document_id'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_job_document_id'), table_name='job')
    op.drop_index(op.f('ix_job_collection_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_document_metadata_field_id'), table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_index(op.f('ix_chunk_parent_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_index('ix_chunk_document_config', table_name='chunk')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_block_parent_id'), table_name='block')
    op.drop_index(op.f('ix_block_document_id'), table_name='block')
    op.drop_table('block')
    op.drop_table('metadata_field')
    op.drop_index(op.f('ix_document_source_hash'), table_name='document')
    op.drop_index(op.f('ix_document_pdf_blob_hash'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_config_version_collection_id'), table_name='config_version')
    op.drop_table('config_version')
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_table('collection')
    op.drop_table('blob')
    op.drop_table('app_user')
    # ### end Alembic commands ###
