# ====== Code Summary ======
# create the `audit_log` table — the append-only trail of every mutating /api/v1 action
#
# Revision: b7d3f1a8c204
# Revises: a3f7c2e91b64
# Created: 2026-09-02 00:00:00.000000
#
# Adds one new table, ``audit_log``: one immutable row per mutating API action (who/when/what/outcome),
# written by a request-scoped middleware and read back by a root-only, paginated+filtered endpoint.
#
# Key design choices:
# - PK is a BIGINT IDENTITY (GENERATED BY DEFAULT AS IDENTITY), NOT the schema's usual app-generated
#   UUID v4. This table is append-heavy and is never the target of a foreign key, so a monotonic
#   server-generated key gives sequential btree insert locality on the hot INSERT path (no random-UUID
#   page-split churn) and a stable tiebreaker for keyset pagination when many rows share one
#   ``created_at`` under a burst (ORDER BY created_at DESC, id DESC).
# - The actor columns (``actor_user_id``, ``actor_key_id``) carry NO foreign key. An audit row is a
#   permanent historical fact: it must survive — and must never block — deletion of the user/key it
#   references, and it keeps the raw actor id for forensics after that actor is gone. ``actor_label``
#   is the human-readable fallback so the log reads without joins.
# - ``path`` stores the low-cardinality ROUTE TEMPLATE ("/api/v1/collections/{id}/reingest"), not the
#   concrete path, so ``(target_type, target_id, ...)`` — parsed by the middleware — carries the id.
#
# Five read-path btree indexes back the endpoint's filters + the age-based retention prune: a global
# ``created_at DESC``; per-actor ``(actor_key_id|actor_user_id, created_at DESC)``; per-resource
# ``(target_type, target_id, created_at DESC)``; and a plain ``correlation_id``. The DESC composites
# use the ``text("created_at DESC")`` form already proven to reconcile cleanly under ``--autogenerate``
# on ``job``/``document``, so they are also declared on the model's ``__table_args__``.
#
# Data safety: STRICTLY ADDITIVE and fully reversible. The upgrade only CREATEs a brand-new table and
# its indexes; no existing table, column, constraint, or data is touched. The downgrade DROPs exactly
# that table (and, with it, its indexes) — irreversible only in the ordinary sense that it discards the
# audit rows accumulated since the upgrade, which is expected for dropping a log table.

# ====== Third-Party Library Imports ======
import sqlalchemy as sa
from alembic import op

# Revision identifiers used by Alembic.
revision = "b7d3f1a8c204"
down_revision = "a3f7c2e91b64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create the ``audit_log`` table and its five read-path indexes."""
    # 1. The table: bigint-identity PK, server-set created_at, FK-free actor columns, action + target
    #    + outcome. Constraint names follow the schema's NAMING_CONVENTION (pk_audit_log).
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_key_id", sa.Uuid(), nullable=True),
        sa.Column("actor_label", sa.String(length=128), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=255), nullable=True),
        sa.Column("status_code", sa.SmallInteger(), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )

    # 2. Read-path indexes for the endpoint filters + retention prune. The DESC ordering on created_at
    #    is expressed via raw text in the composite indexes (create_index column lists can't carry a
    #    per-column DESC); it matches the model's ``text("created_at DESC")`` declarations exactly.
    op.create_index(
        "ix_audit_log_created_at", "audit_log", [sa.text("created_at DESC")], unique=False
    )
    op.create_index(
        "ix_audit_log_actor_key_created",
        "audit_log",
        ["actor_key_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_actor_user_created",
        "audit_log",
        ["actor_user_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_target_created",
        "audit_log",
        ["target_type", "target_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_audit_log_correlation_id", "audit_log", ["correlation_id"], unique=False)


def downgrade() -> None:
    """Drop the ``audit_log`` table and its indexes (discards accumulated audit rows)."""
    # 1. Drop the indexes explicitly, then the table (drop_table would cascade them, but explicit
    #    drops keep the downgrade symmetric with the upgrade and independent of drop order).
    op.drop_index("ix_audit_log_correlation_id", table_name="audit_log")
    op.drop_index("ix_audit_log_target_created", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_user_created", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_key_created", table_name="audit_log")
    op.drop_index("ix_audit_log_created_at", table_name="audit_log")

    # 2. Drop the table itself.
    op.drop_table("audit_log")
