# ====== Code Summary ======
# create the `idempotency_key` table — a Stripe-style Idempotency-Key store
#
# Revision: c9a4e1b7f302
# Revises: b7d3f1a8c204
# Created: 2026-09-02 00:00:00.000000
#
# Adds one new table, ``idempotency_key``: one row per (actor, method+route, client key). A
# request-scoped middleware INSERTs an in-progress row on the first mutating POST carrying an
# ``Idempotency-Key`` header, runs the handler once, then caches the response on the same row so
# retries replay it instead of re-executing. Mirrors the ORM model exactly
# (shared_libs...tables/observability/idempotency_key.py) — env.py runs compare_type=True, so any
# type/width/nullability drift would surface on the next --autogenerate.
#
# Key design choices:
# - PK is a BIGINT IDENTITY (GENERATED BY DEFAULT AS IDENTITY), NOT the schema's usual app-generated
#   UUID v4: the table is append-heavy (one row per mutating request) and never the target of a
#   foreign key, so a monotonic server-generated key gives sequential btree insert locality on the hot
#   INSERT path. The row's dedup *identity* is the UNIQUE constraint, not this surrogate.
# - UNIQUE (actor_scope, method, path, idempotency_key) — named ``uq_idempotency_key_scope`` — is THE
#   dedup key, the lookup index, AND the concurrency guard: two concurrent first-requests race to
#   INSERT and the loser gets an IntegrityError on this constraint, which the middleware treats as
#   "already in progress" (409). ``actor_scope`` is a NEVER-NULL text identity (e.g. "key:<uuid>",
#   "user:<uuid>", "anon") precisely so no NULL leaks into the unique key — a NULL would be treated as
#   distinct by Postgres and defeat dedup whenever auth is off.
# - No foreign key on any actor id: the row must survive actor deletion; the identity is captured as
#   text in ``actor_scope``.
# - ``state`` uses value_enum = Enum(native_enum=False): rendered as sa.Enum(...) whose VARCHAR width
#   is derived from the longest member value ("in_progress" -> 11) and which adds NO CHECK constraint.
#   The ORM carries a Python-side default (default=in_progress, not server_default), so this migration
#   emits NO server DEFAULT on it — the app supplies it on insert, keeping the schema drift-free.
# - ``response_body`` is BYTEA (LargeBinary) so any response content-type round-trips byte-exact on
#   replay. It, ``response_status`` and ``response_media_type`` are NULL while state is in_progress.
#
# One read-path btree index (``ix_idempotency_key_expires_at``) backs the TTL prune cron, which
# deletes rows WHERE expires_at < now(); a plain (non-partial) index suffices since every row is
# eventually eligible.
#
# Data safety: STRICTLY ADDITIVE and fully reversible. The upgrade only CREATEs a brand-new table with
# its unique constraint and index; no existing table, column, constraint, or data is touched. The
# downgrade DROPs exactly that table — irreversible only in the ordinary sense that it discards the
# idempotency records accumulated since the upgrade (expected when dropping a cache/dedup table).

# ====== Third-Party Library Imports ======
import sqlalchemy as sa
from alembic import op

# Revision identifiers used by Alembic.
revision = "c9a4e1b7f302"
down_revision = "b7d3f1a8c204"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create the ``idempotency_key`` table, its unique dedup constraint, and the TTL prune index."""
    # 1. The table: bigint-identity PK, never-null actor_scope + endpoint scope + client key, request
    #    fingerprint, lifecycle state, the cached response (nullable while in_progress), and the TTL
    #    timestamps. Constraint names follow the schema's NAMING_CONVENTION (pk_idempotency_key).
    op.create_table(
        "idempotency_key",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("actor_scope", sa.String(length=160), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum("in_progress", "completed", name="idempotencystate", native_enum=False),
            nullable=False,
        ),
        sa.Column("response_status", sa.SmallInteger(), nullable=True),
        sa.Column("response_body", sa.LargeBinary(), nullable=True),
        sa.Column("response_media_type", sa.String(length=128), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_key")),
        # THE dedup key + lookup index + concurrency guard. The backend catches the IntegrityError on
        # this exact constraint name to serve the concurrent-first-request 409.
        sa.UniqueConstraint(
            "actor_scope",
            "method",
            "path",
            "idempotency_key",
            name="uq_idempotency_key_scope",
        ),
    )

    # 2. TTL prune index: the retention cron deletes WHERE expires_at < now().
    op.create_index(
        "ix_idempotency_key_expires_at", "idempotency_key", ["expires_at"], unique=False
    )


def downgrade() -> None:
    """Drop the ``idempotency_key`` table and its index (discards accumulated idempotency records)."""
    # 1. Drop the prune index, then the table (the unique constraint drops with the table).
    op.drop_index("ix_idempotency_key_expires_at", table_name="idempotency_key")
    op.drop_table("idempotency_key")
